[package]
name = "dgim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
serde = { version = "1.0.199", features = ["derive"] }
sqlite = "0.36.0"
toml = "0.8.12"
